
(defrule early0
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earlier )
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (id-wsd_word_mng ?id pahale_kA))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_word_mng  " ?*wsd_dir* "  early.clp  	early0   "  ?id "  pahale_kA )" crlf))
)

; earlier version
(defrule early1
(declare (salience 4900))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earlier )
(id-cat_coarse ?id adverb)
=>
(retract ?mng)
(assert (id-wsd_word_mng ?id isase_pahale))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_word_mng  " ?*wsd_dir* "  early.clp  	early1   "  ?id "  isase_pahale )" crlf))
)

;"earlier","Adv","1.pahale_[kA]"
;The workers went on vacation earlier in this season.
;
;Rules generated by wasp machine
(defrule early2
(declare (salience 4800))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earliest )
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (id-wsd_word_mng ?id SurU_SurU_meM))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_word_mng  " ?*wsd_dir* "  early.clp  	early2   "  ?id "  SurU_SurU_meM )" crlf))
)



;Added by Meena(6.9.10)
;The project will start early next month .
(defrule early3
(declare (salience 4600))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(or(kriyA-kAlavAcI  ?id1 ?kAlv)(kriyA-in_saMbanXI  ?id1 ?saM))  
(not(or(id-root ?kAlv morning|evening|night)(id-root ?saM morning|evening|night)))
(kriyA-kriyA_viSeRaNa  ?id1 ?id)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id SurU_meM))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early3   "  ?id " SurU_meM  )" crlf))
)



;Added by Meena(6.9.10)
;I got up early in the morning . 
(defrule early4
(declare (salience 4600))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(or(kriyA-in_saMbanXI  ?id1 ?saM)(kriyA-kAlavAcI  ?id1 ?kAlv))
(not(or(id-root ?kAlv month|year|week)(id-root ?saM month|year|week)))
(kriyA-kriyA_viSeRaNa  ?id1 ?id)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id jalxI))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early4   "  ?id "  jalxI )" crlf))
)



;Salience reduced and meaning changed by Meena(6.9.10)
(defrule early5
(declare (salience 0))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-cat_coarse ?id adverb)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id jalxI))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp 	early5   "  ?id "  jalxI )" crlf))
)


;"early","Adv","1.jalxI"
;He has to go to school early today .


;$$$ Modified by Pramila(BU) on 12-12-2013 ;Added 'breakfast in the action part.
;Modified by Meena(23.9.10)
;Added by Meena(7.9.10)
;These are some of my early attempts at sculpture .
;He must get up early in the morning .
;The next morning they sat down to an early breakfast.
(defrule early6
(declare (salience 4700))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(viSeRya-viSeRaNa ?id1 ?id)
(id-word ?id1 ?word)
=>
(retract ?mng)
(if (or(eq ?word morning)(eq ?word breakfast)) then
    (assert (id-wsd_root_mng ?id jalxI))
else	;Added else statement and moved assert statement into else part ( by Roja(12-09-13) )
(assert (id-wsd_root_mng ?id prAramBika))
)
(if ?*debug_flag* then
(if (or(eq ?word morning)(eq ?word breakfast)) then
        (printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp      early6   "  ?id "  jalxI )" crlf)
else
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early6   "  ?id " prAramBika  )" crlf)
)
))


;Added by Meena(7.9.10)
;We meet the hero quite early in the film . 
(defrule early7
(declare (salience 4700))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(viSeRaNa-viSeRaka ?id ?id1)
;(viSeRya-in_saMbanXI  ?id ?)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id AramBa_meM))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early7   "  ?id " AramBa_meM  )" crlf))
)



;Added by Meena(7.9.10)
(defrule early8
(declare (salience 0))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id AramBika))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early8   "  ?id " AramBika  )" crlf))
)

(defrule early9
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earlier )
(viSeRya-viSeRaNa  ?id1 ?id)
(id-root ?id1 time)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (affecting_id-affected_ids-wsd_group_root_mng ?id ?id1 prAcIna_kAla))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-affecting_id-affected_ids-wsd_group_root_mng   " ?*wsd_dir* " early.clp	early9  "  ?id "  " ?id1 "  prAcIna_kAla  )" crlf))
)


(defrule early10
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(viSeRya-viSeRaka  ?id ?id1)
(id-root ?id1 too)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (affecting_id-affected_ids-wsd_group_root_mng ?id ?id1 bahuwa_jalxI))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-affecting_id-affected_ids-wsd_group_root_mng   " ?*wsd_dir* " early.clp	early10  "  ?id "  " ?id1 "  bahuwa_jalxI  )" crlf))
)


;@@@ Added by Pramila (BU) on 17-02-2014
; One kind of response from the earliest times has been to observe the physical environment carefully look for any meaningful patterns 
;and relations in natural phenomena and build and use new tools to interact with nature.   ;ncert
;आदि काल से मानव की एक प्रकार की प्रतिक्रिया यह रही है कि उसने अपने भौतिक पर्यावरण का सावधानीपूर्वक प्रेक्षण किया है, प्राकृतिक परिघटनाओं में अर्थपूर्ण पैटर्न तथा सम्बन्ध खोजे हैं, तथा प्रकृति 
;के साथ प्रतिक्रिया कर सकने के लिए नए औजारों को बनाया तथा उनका उपयोग किया है.
(defrule early11
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earliest )
(viSeRya-viSeRaNa  ?id1 ?id)
(id-root ?id1 time)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (affecting_id-affected_ids-wsd_group_word_mng ?id ?id1 Axi_kAla))
(assert (id-eng-src ?id earliest Word_mng))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-affecting_id-affected_ids-wsd_group_word_mng   " ?*wsd_dir* " early.clp	early11  "  ?id "  " ?id1 "  Axi_kAla  )" crlf))
)

;@@@ Added by Pramila(Banasthali University) on 24-02-2014
;Early thinkers like Aristotle had wrong ideas about it.  ;ncert
;आद्य विचारकों जैसे अरस्तू की बल के विषय में सङ्कल्पना गलत थी.
(defrule early12
(declare (salience 4500))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(viSeRya-viSeRaka  ?id1 ?id)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id Axya))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early12   "  ?id " Axya  )" crlf))
)

;@@@ Added by Pramila(Banasthali University) on 24-02-2014
;The project will start early next month .   [old clp]
;परियोजना अगले महीने के शुरू में आरम्भ होगी.
(defrule early13
(declare (salience 4600))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(viSeRya-viSeRaka  ?kAlv ?id)
(kriyA-kAlavAcI  ?id1 ?kAlv)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id SurU_meM))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early13   "  ?id " SurU_meM  )" crlf))
)

;@@@ Added by Pramila(Banasthali University) on 04-03-2014
;The government is pressing for an early resolution of the dispute.   ;oald
;सरकार विवाद के शीघ्र समाधान के लिये दबाव डाल रही है .
(defrule early12
(declare (salience 4800))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(viSeRya-viSeRaNa  ?id1 ?id)
(id-root ?id1 resolution)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id SIGra))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp     early12   "  ?id " SIGra  )" crlf))
)

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule sub_samA_early6
(declare (salience 4700))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(subject-subject_samAnAXikaraNa ?id1 ?id)
(id-word ?id1 ?word)
=>
(retract ?mng)
(if (or(eq ?word morning)(eq ?word breakfast)) then
    (assert (id-wsd_root_mng ?id jalxI))
else	;Added else statement and moved assert statement into else part ( by Roja(12-09-13) )
(assert (id-wsd_root_mng ?id prAramBika))
)
(if ?*debug_flag* then
(if (or(eq ?word morning)(eq ?word breakfast)) then
        (printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp      early6   "  ?id "  jalxI )" crlf)
else
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng " ?*wsd_dir* " early.clp   sub_samA_early6   "   ?id " prAramBika )" crlf)
)
))

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule obj_samA_early6
(declare (salience 4700))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(object-object_samAnAXikaraNa ?id1 ?id)
(id-word ?id1 ?word)
=>
(retract ?mng)
(if (or(eq ?word morning)(eq ?word breakfast)) then
    (assert (id-wsd_root_mng ?id jalxI))
else	;Added else statement and moved assert statement into else part ( by Roja(12-09-13) )
(assert (id-wsd_root_mng ?id prAramBika))
)
(if ?*debug_flag* then
(if (or(eq ?word morning)(eq ?word breakfast)) then
        (printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng   " ?*wsd_dir* "  early.clp      early6   "  ?id "  jalxI )" crlf)
else
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng " ?*wsd_dir* " early.clp   obj_samA_early6   "   ?id " prAramBika )" crlf)
)
))

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule sub_samA_early9
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earlier )
(subject-subject_samAnAXikaraNa ?id1 ?id)
(id-root ?id1 time)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (affecting_id-affected_ids-wsd_group_root_mng ?id ?id1 prAcIna_kAla))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-affecting_id-affected_ids-wsd_group_root_mng " ?*wsd_dir* " early.clp   sub_samA_early9   "   ?id " " ?id1 " prAcIna_kAla )" crlf))
)

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule obj_samA_early9
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earlier )
(object-object_samAnAXikaraNa ?id1 ?id)
(id-root ?id1 time)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (affecting_id-affected_ids-wsd_group_root_mng ?id ?id1 prAcIna_kAla))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-affecting_id-affected_ids-wsd_group_root_mng " ?*wsd_dir* " early.clp   obj_samA_early9   "   ?id " " ?id1 " prAcIna_kAla )" crlf))
)

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule sub_samA_early11
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earliest )
(subject-subject_samAnAXikaraNa ?id1 ?id)
(id-root ?id1 time)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (affecting_id-affected_ids-wsd_group_word_mng ?id ?id1 Axi_kAla))
(assert (id-eng-src ?id earliest Word_mng))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-affecting_id-affected_ids-wsd_group_word_mng " ?*wsd_dir* " early.clp   sub_samA_early11   "   ?id " " ?id1 " Axi_kAla )" crlf))
)

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule obj_samA_early11
(declare (salience 5000))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(id-word ?id earliest )
(object-object_samAnAXikaraNa ?id1 ?id)
(id-root ?id1 time)
(id-cat_coarse ?id adjective)
=>
(retract ?mng)
(assert (affecting_id-affected_ids-wsd_group_word_mng ?id ?id1 Axi_kAla))
(assert (id-eng-src ?id earliest Word_mng))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-affecting_id-affected_ids-wsd_group_word_mng " ?*wsd_dir* " early.clp   obj_samA_early11   "   ?id " " ?id1 " Axi_kAla )" crlf))
)

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule sub_samA_early12
(declare (salience 4800))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(subject-subject_samAnAXikaraNa ?id1 ?id)
(id-root ?id1 resolution)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id SIGra))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng " ?*wsd_dir* " early.clp   sub_samA_early12   "   ?id " SIGra )" crlf))
)

;@@@ Added by Sukhada (12-05-14). Automatically generated this rule.
(defrule obj_samA_early12
(declare (salience 4800))
(id-root ?id early)
?mng <-(meaning_to_be_decided ?id)
(object-object_samAnAXikaraNa ?id1 ?id)
(id-root ?id1 resolution)
=>
(retract ?mng)
(assert (id-wsd_root_mng ?id SIGra))
(if ?*debug_flag* then
(printout wsd_fp "(dir_name-file_name-rule_name-id-wsd_root_mng " ?*wsd_dir* " early.clp   obj_samA_early12   "   ?id " SIGra )" crlf))
)
