(load*  "multi_word_expressions.clp")
(bsave  "multi_word_expressions.bclp")
(clear)
(load* "word_without_adverb.clp")
(bsave "word_without_adverb.bclp")
(clear)
(load*  "parserid_wordid_mapping.clp")
(bsave  "parserid_wordid_mapping.bclp")
(clear)
(load*  "lwgid_wordid_mapping.clp")
(bsave  "lwgid_wordid_mapping.bclp")
(clear)
(load*  "cat_rule.clp")
(bsave  "cat_rule.bclp")
(clear)
(load*  "root_rule.clp")
(bsave  "root_rule.bclp")
(clear)
(load*  "lwg_rules.clp")
(bsave  "lwg_rules.bclp")
(clear)
(load*  "parser_id_mapping.clp")
(bsave  "parser_id_mapping.bclp")
(clear)
(load*  "hindi_meaning.clp")
(bsave  "hindi_meaning.bclp")
(clear)
(load*  "causative_verb_mng.clp")
(bsave  "causative_verb_mng.bclp")
(clear)
(load*  "preferred_morph_consistency_check.clp")
(bsave  "preferred_morph_consistency_check.bclp")
(clear)
(load*  "tam_id.clp")
(bsave  "tam_id.bclp")
(clear)
(load*  "tam_meaning.clp")
(bsave  "tam_meaning.bclp")
(clear)
(load*  "gender_info.clp")
(bsave  "gender_info.bclp")
(clear)
(load*  "vibakthi.clp")
(bsave  "vibakthi.bclp")
(clear)
(load*  "agreement.clp")
(bsave  "agreement.bclp")
(clear)
(load*  "number.clp")
(bsave  "number.bclp")
(clear)
(load*  "GNP_agreement.clp")
(bsave  "GNP_agreement.bclp")
(clear)
(load* "hindi_sent_reorder.clp")
(bsave "hindi_sent_reorder.bclp")
(clear)
(load*  "prepare_apertium_input.clp")
(bsave  "prepare_apertium_input.bclp")
(clear) 
(load*  "padasuthra.clp")
(bsave  "padasuthra.bclp")
(clear)
(load*  "English_sentence.clp")
(bsave  "English_sentence.bclp")
(clear)
(load*  "hindi_sentence.clp")
(bsave  "hindi_sentence.bclp")
(clear)
;======== Link Parser files ===============

(load* "link_category.clp")
(bsave "link_category.bclp")
(clear)
(load*  "combining_apostrophe.clp")
(bsave  "combining_apostrophe.bclp")
(clear)
(load*  "verb_chunk.clp")
(bsave  "verb_chunk.bclp")
(clear)
(load*  "lwg_not.clp")
(bsave  "lwg_not.bclp")
(clear)
(load*  "link_relation_rules.clp")
(bsave  "link_relation_rules.bclp")
(clear)
(load*  "idiomatic_expressions.clp")
(bsave  "idiomatic_expressions.bclp")
(clear)
(load*  "lwg_consistency_check.clp")
(bsave  "lwg_consistency_check.bclp")
(clear)
(load*  "hindi_position.clp")
(bsave  "hindi_position.bclp")
(clear)
;======== Open Logos Parser files ==============
(load*  "ol_parser_id_mapping.clp")
(bsave  "ol_parser_id_mapping.bclp")
(clear)
(load*  "modify_ol_relations.clp")
(bsave  "modify_ol_relations.bclp")
(clear)
(load*  "modify_ol_cat.clp")
(bsave  "modify_ol_cat.bclp")
(clear)
(load*  "ol_parserid_wordid_mapping.clp")
(bsave  "ol_parserid_wordid_mapping.bclp")
(clear)
(load*  "lwg_disambiguation.clp")
(bsave  "lwg_disambiguation.bclp")
(clear)
;========== Stanford Parser files =================
(load*  "sd_relation_rules.clp")
(bsave  "sd_relation_rules.bclp")
(clear)
(load*  "sd_combining_apostrophe.clp")
(bsave  "sd_combining_apostrophe.bclp")
(clear)
(load*  "sd_category.clp")
(bsave  "sd_category.bclp")
(clear)
(load*  "sd_lwg_rules.clp")
(bsave  "sd_lwg_rules.bclp")
(clear)
(load*  "sd_pada.clp")
(bsave  "sd_pada.bclp")
(clear)
(load*  "H_ordering_rules.clp")
(bsave  "H_ordering_rules.bclp")
(clear)
(load*  "get_constituency_tree.clp")
(bsave  "get_constituency_tree.bclp")
(clear)
(load*  "parser_tree_correction_rules.clp")
(bsave  "parser_tree_correction_rules.bclp")
(clear)
(load*  "parser_tree_modification_rules.clp")
(bsave  "parser_tree_modification_rules.bclp")
(clear)
(exit)
