 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/prepare_minion_for_multiple_sen.clp"))
 (load ?*path*)
 (load-facts "id_Apertium_output.dat")
 (load-facts "hindi_id_order.dat")
 (open "minion_input.txt" min_fp "w")
 (run)
 (save-facts "multiple_mngs.dat" local id-hnd_mng)
 (close min_fp)
 (exit)

