(load "path_for_html.clp")
(bind ?path1 ?*path*)
(bind ?*path* (str-cat ?*path* "/Anu_clp_files/create_xml_file.clp"))
(load ?*path*)
(bind ?mypath1 ?*mypath*)
(bind ?path2 (str-cat ?*mypath* "/tmp/" ?*filename* "_tmp/dir_names.txt"))
(open ?path2  op_fp "r")
(bind ?s_no (readline op_fp))
(bind ?*mypath* (str-cat ?*mypath* "/tmp/" ?*filename* "_tmp/"?s_no"/all_facts"))
(close op_fp)
(load-facts ?*mypath*)
(bind ?mypath1 (str-cat ?*filename* "_tmp.html"))
(open ?mypath1 fp "w")
;(watch all)
(run)
(close fp)
(exit)

