 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/lwg_rules.bclp"))
 (bload ?*path*)
 (load-facts "word_info_w_adv.dat")
 (load-facts "original_word.dat")
 (load-facts "preferred_morph_tmp.dat")
 (load-facts "morph.dat")
 (load-facts "root_tmp.dat")
 (load-facts "lwgid_wordid_mapping.dat")
 (load-facts "parserid_wordid_mapping.dat")
 (open "lwg_info_tmp.dat" old_lwg_file "a")
 (run)
 (close old_lwg_file)
 (clear)
