 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/verb_chunk.bclp"))
 (bload ?*path*)
 (load-facts "link_relation_info_tmp1.dat")
 (load-facts "link_name_expand.dat")
 (load-facts "root_tmp.dat")
 (load-facts "morph.dat")
 (load-facts "preferred_morph_tmp.dat")
 (load-facts "linkid_word.dat")
 (open "lwg_ids.dat" lwg_fp "a")
 (open "lwg_debug.dat" lwg_db_fp "a")
 (run)
 (close lwg_fp)
 (close lwg_db_fp)
 (clear)
;;-------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/lwg_not.bclp"))
 (bload ?*path*)
 (load-facts "lwg_ids.dat")
 (load-facts "link_relation_info_tmp1.dat")
 (load-facts "link_name_expand.dat")
 (load-facts "linkid_word.dat")
 (open "lwg_info_tmp.dat" lwg_info_fp "a")
 (run)
 (clear)

