 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/user_wsd_info.clp"))
 (load ?*path*)
 (load-facts "cat_consistency_check.dat")
 (load-facts "word.dat")
 (load-facts "root.dat")
 (load-facts "relations_tmp1.dat")
 (load-facts "original_word.dat")
 (load-facts "English_sentence.dat")
 (open "user_wsd_info.dat" rel_wd_fp "a")
 (assert (next_id 1))
 (run)
 (clear)
 ;--------------------------------------------------------------------------
; (load "global_path.clp")
; (bind ?*path* (str-cat ?*path* "/Anu_clp_files/eng_hin_pos.clp"))
; (load ?*path*)
; (load-facts "Eng_id_order.dat")
; (load-facts "hindi_id_order.dat")
; (load-facts "lwg_info.dat")
; (load-facts "GNP_agmt_info.dat")
; (load-facts "hindi_meanings.dat")
; (load-facts "hindi_meanings_tmp1.dat")
; (load-facts "word.dat")
; (load-facts "id_Apertium_output.dat")
; (assert (index 1))
; (assert (English))
; (open "position.dat" pos_fp "a")
; (run)
; (close pos_fp)
; (clear)
 ;--------------------------------------------------------------------------
 (exit)
