 (load* global_path.clp)
 (load-facts "word.dat")
 (load-facts "parserid_wordid_mapping.dat")
 (load-facts "lwg_debug.dat")
 (load-facts "lwg_info.dat")
 (load-facts "sd_word_tmp.dat")
 ;(load-facts "relations_tmp.dat")
 (load-facts "link_name_expand.dat")
 (load-facts "link_relation_info_tmp1.dat")
 ;(load-facts "parserid_word_tmp.dat")
 (load-facts "English_sentence.dat")
 (load-facts "parser_type.dat")
 (batch* "lwg_debug.clp") 
 (run)
