 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/English_sentence.bclp"))
 (bload ?*path*)
 (load-facts "word.dat")
 (load-facts "vibakthi_info.dat")
 (load-facts "punctuation_info.dat")
 (load-facts "hindi_id_order.dat")
 (open "hin_eng_sent.dat" e_sen_fp "w")
 (run)
 (clear)
 ;----------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/hindi_sentence.bclp"))
 (bload ?*path*)
 (load-facts "word.dat")
 (load-facts "parser_type.dat")
 (load-facts "id_Apertium_output.dat")
 (load-facts "hindi_id_order.dat")
 (load-facts "hindi_punctuation.dat")
 (load-facts "punctuation_info.dat")
 (load-facts "original_word.dat")
 (load-facts "underscore_hyphen_replace_info.dat")
 (load-facts "wsd_facts_output.dat")
 (load-facts "GNP_agmt_info.dat")
 (load-facts "hindi_meanings.dat")
 (open "hindi_sentence_tmp.dat" h_sen_fp "w")
 (open "removed_repeated_mng.dat" rm_mng_fp "w")
 (run)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/eng_hin_pos.clp"))
 (load ?*path*)
 (load-facts "Eng_id_order.dat")
 (load-facts "hindi_id_order.dat")
 (load-facts "lwg_info.dat")
 (load-facts "GNP_agmt_info.dat")
 (load-facts "hindi_meanings.dat")
 (load-facts "hindi_meanings_with_grp_ids.dat")
 (load-facts "original_word.dat")
 (load-facts "id_Apertium_output.dat")
 (assert (index 1))
 (assert (English_Sen))
 (open "position.dat" pos_fp "w")
 (run)
 (save-facts "Eng_sen_without_punct.dat" local English_Sen)
 (close pos_fp)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/MINION/alignment/get_dbase_mng.clp"))
 (load ?*path*)
 (load-facts "revised_root.dat")
 (load-facts "original_word.dat")
 (load-facts "cat_consistency_check.dat")
 (load-facts "lwg_info.dat")
 (load-facts "sen_phrase.dat")
 (load-facts "Eng_sen_without_punct.dat")
 (assert (default-cat))
 (run)
 (save-facts "database_mng.dat" local id-org_wrd-root-dbase_name-mng e_tam-id-dbase_name-mng id-multi_word_expression-dbase_name-mng multi_word_expression-grp_ids id-left_word-possible_mngs id-right_word-possible_mngs)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/get_manual_id_en_hi.clp"))
 (load ?*path*)
 (load-facts "manual_hindi_sen.dat")
 (load-facts "manual_hin.morph.dat")
 (load-facts "word-alignment.dat")
 (load-facts "database_mng.dat")
 (load-facts "revised_root.dat")
 (load-facts "id_Apertium_output.dat")
 (open "alignment_dic.txt" dic_fp "a")
 (run)
 (close dic_fp)
 (save-facts "manual_word.dat" local manual_id-word)
 (save-facts "manual_lwg_en_hi.dat" local manual_id_en_hi-word-root-vib-grp_ids)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/get_manual_id_en_hi1.clp"))
 (load ?*path*)
 (load-facts "manual_hindi_sen.dat")
 (load-facts "manual_hin.morph.dat")
 (load-facts "word-alignment-hi-en.dat")
 (load-facts "database_mng.dat")
 (load-facts "revised_root.dat")
 (load-facts "id_Apertium_output.dat")
 (open "alignment_dic.txt" dic_fp "a")
 (run)
 (close dic_fp)
 (save-facts "manual_word_hi_en.dat" local manual_id-word)
 (save-facts "manual_lwg_hi_en.dat" local manual_id_en_hi-word-root-vib-grp_ids)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/word_alignment.clp"))
 (load ?*path*)
 (load-facts "manual_word.dat")
 (load-facts "manual_lwg_en_hi.dat")
 (load-facts "manual_hindi_sen.dat")
 (load-facts "manual_hin.morph.dat")
 (load-facts "word-alignment.dat")
 (load-facts "database_mng.dat")
 (load-facts "revised_root.dat")
 (load-facts "id_Apertium_output.dat")
 (load-facts "GNP_agmt_info.dat")
 (load-facts "word.dat")
 (load-facts "original_word.dat")
 (open "alignment_dic.txt" dic_fp "a")
 (run)
 (save-facts "word_alignment_tmp.dat" local anu_id-anu_mng-sep-man_id-man_mng_tmp)
 ;(save-facts "word_alignment_tmp.dat" local anu_id-anu_mng-sep-man_id-man_mng anu_id-anu_mng-sep-man_id-man_mng_tmp)
 (save-facts "potential_assignment.dat" local potential_assignment_vacancy_id-candidate_id)
 (save-facts "anu_aligned_ids_tmp.dat" local mng_has_been_filled)
 (save-facts "man_aligned_ids_tmp.dat" local mng_has_been_aligned)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/word_alignment.clp"))
 (load ?*path*)
 (load-facts "manual_word_hi_en.dat")
 (load-facts "manual_lwg_hi_en.dat")
 (load-facts "manual_hindi_sen.dat")
 (load-facts "manual_hin.morph.dat")
 (load-facts "word-alignment-hi-en.dat")
 (load-facts "database_mng.dat")
 (load-facts "revised_root.dat")
 (load-facts "id_Apertium_output.dat")
 (load-facts "GNP_agmt_info.dat")
 (load-facts "word.dat")
 (load-facts "original_word.dat")
 (open "alignment_dic.txt" dic_fp "a")
 (run)
 (save-facts "word_alignment_hi_en_tmp1.dat" local anu_id-anu_mng-sep-man_id-man_mng_tmp)
 (save-facts "potential_assignment_hi_en.dat" local potential_assignment_vacancy_id-candidate_id)
 (save-facts "anu_aligned_ids_tmp_hi_en.dat" local mng_has_been_filled)
 (save-facts "man_aligned_ids_tmp_hi_en.dat" local mng_has_been_aligned)
 (clear)
 ;--------------------------------------------------------------------------
; (load "global_path.clp")
; (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/get_manual_id_hi_en.clp"))
; (load ?*path*)
; (load-facts "manual_hindi_sen.dat")
; (load-facts "manual_hin.morph.dat")
; (load-facts "word-alignment-hi-en.dat")
; (load-facts "manual_word.dat")
; (run)
; (save-facts "manual_lwg_hi_en.dat" local manual_id_hi_en-word-root-vib-grp_ids)
; (clear)
 ;--------------------------------------------------------------------------
; (load "global_path.clp")
; (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/alignment.clp"))
; (load ?*path*)
; (load-facts "manual_hindi_sen.dat")
; (load-facts "word-alignment.dat")
; (load-facts "id_Apertium_output.dat")
; (assert (current_id 1))
; (open "word_alignment.dat" align_fp "w")
; (run)
; (save-facts "manual_ids.dat" local manual_ids)
; (close align_fp)
; (clear)
 ;--------------------------------------------------------------------------
; (load "global_path.clp")
; (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/word_alignment.clp"))
; (load ?*path*)
; (load-facts "word-alignment.dat")
; (load-facts "database_mng.dat")
; (load-facts "id_Apertium_output.dat")
; (load-facts "revised_root.dat")
; (load-facts "original_word.dat")
; (run)
; (save-facts "word_alignment.dat" local anu_id-anu_mng-man_mng)
; (clear)
 ;--------------------------------------------------------------------------
; (load "global_path.clp")
; (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/create_alignment_dic.clp"))
; (load ?*path*)
; (load-facts "word-alignment.dat")
; (load-facts "database_mng.dat")
; (open "alignment_dic.txt" dic_fp "a")
; (run)
; (close dic_fp)
 (exit)
