#define PARA_LN_WRD_NO 0
#define LEFT_TAG 1
#define WORD 2
#define RIGHT_TAG 3
#define MORPH 4
#define ROOT 5
#define POS 6
#define CHUNK 7
#define uccAraNa 8
#define paxasUwra 9
#define TAM 10
#define paxasUwra_LWG 11
#define SOURCE_LANGUAGE_LWG 12
#define SHALLOW_PARSER_RELATIONS 13
#define WSD 14
#define WN_WSD 15
#define PARSE_POS 16
#define PARSE_REL 17
#define CBOUND 18
#define TR 19
#define AGMT 20
#define N_VIB 21
#define V_VIB 22
#define NUMBER 23
#define PERSON 24
#define GENDER 25
#define PREP_MV 26
#define TARGET_LANG 27
#define HEAD 28
#define TARGET_LANG_AT_HD 29
#define TARGET_LANG_ORDER 30
#define TARGET_LANG_LEFT_TAG 31
#define TARGET_LANG_RIGHT_TAG 32
#define SOURCE_LANG_AT_HD 33

