(load "global_path.clp")
(bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/MINION/alignment/get_slot_number.clp"))
(load ?*path*)
(load-facts "minion.dat")
(load-facts "manual_lwg_new.dat")
(load-facts "manual_word.dat")
(load-facts "id_Apertium_output.dat")
(load-facts "hindi_id_order.dat")
;(load-facts "anu_slot_id-minion_slot_id_mapping.dat")
;(watch facts)
;(watch rules)
(run)
(save-facts "word_alignment.dat" local anu_id-anu_mng-sep-man_id-man_mng)
(exit)
