 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/MINION/alignment/get_grp_info1.clp"))
 (load ?*path*)
 (load-facts "sd_scope.dat")
 (load-facts "pada_id_info.dat")
 (load-facts "cat_consistency_check.dat")
 (load-facts "hindi_id_order_for_minion.dat")
 (load-facts "word.dat")
 (load-facts "multi_word_expressions.dat")
 (load-facts "man_multi_word.dat")
 (run)
 (save-facts "group_info.dat" local grp_ids-slot_ids get_cost_for_grp total_count)
 (clear)
 ;-------------------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/MINION/alignment/prepare_minion_input1.clp"))
 (load ?*path*)
 (load-facts "hindi_id_order_for_minion.dat")
 (load-facts "manual_lwg_new.dat")
 (load-facts "word_alignment_tmp.dat")
 (load-facts "manual_id_mapping.dat")
 (load-facts "potential_assignment.dat")
 (load-facts "pada_id_info.dat")
 (load-facts "English_sentence.dat")
 (load-facts "man_potential_facts.dat")
 (load-facts "group_info.dat")
 (load-facts "manual_hindi_sen.dat")
 (load-facts "database_mng.dat")
 (load-facts "manual_lwg.dat")
 (load-facts "revised_root.dat")
 (open "minion_input.txt" minion_fp "w")
 (run)
 (close minion_fp)
 ;-------------------------------------------------------------------------------------
 (exit)

