 ;----------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/English_sentence.bclp"))
 (bload ?*path*)
 (load-facts "word.dat")
 (load-facts "vibakthi_info.dat")
 (load-facts "punctuation_info.dat")
 (load-facts "hindi_id_order.dat")
 (open "hin_eng_sent.dat" e_sen_fp "a")
 (run)
 (clear)
 ;----------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/hindi_sentence.bclp"))
 (bload ?*path*)
 (load-facts "word.dat")
 (load-facts "parser_type.dat")
 (load-facts "id_Apertium_output.dat")
 (load-facts "hindi_id_order.dat")
 (load-facts "hindi_punctuation.dat")
 (load-facts "punctuation_info.dat")
 (load-facts "original_word.dat")
 (load-facts "underscore_hyphen_replace_info.dat")
 (open "hindi_sentence.dat" h_sen_fp "a")
 (run)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/Anu_clp_files/eng_hin_pos.clp"))
 (load ?*path*)
 (load-facts "Eng_id_order.dat")
 (load-facts "hindi_id_order.dat")
 (load-facts "lwg_info.dat")
 (load-facts "GNP_agmt_info.dat")
 (load-facts "hindi_meanings.dat")
 (load-facts "hindi_meanings_tmp1.dat")
 (load-facts "original_word.dat")
 (load-facts "id_Apertium_output.dat")
 (assert (index 1))
 (assert (English_Sen))
 (open "position.dat" pos_fp "a")
 (run)
 (close pos_fp)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/alignment/get_wx.clp"))
 (load ?*path*)
 (load-facts "hindi_meanings.dat")
 (load-facts "wx_output.dat")
 (load-facts "word.dat")
 (run)
 (save-facts "hin_mng_without_@.dat" local id-HM-source)
 (save-facts "wx_agrep_output.dat" local eng_word-man_wx_word)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/alignment/get_anu_grp_mng.clp"))
 (load ?*path*)
 (load-facts "id_Apertium_output.dat")
 (load-facts "hin_mng_without_@.dat")
 (load-facts "sd_scope.dat")
 (load-facts "GNP_agmt_info.dat")
 (load-facts "to_be_included_in_paxa.dat")
 (open "anu_grp_mng.dat" ap_grp_fp "w")
 (open "aper_op_without_@.dat" ap_fp "w")
 (run)
 (close ap_fp)
 (close ap_grp_fp)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/alignment/get_man_grp_mng.clp"))
 (load ?*path*)
 (load-facts "shallow_parser_GNP_info.dat")
 (load-facts "shallow_parser_output.dat.tmp7")
 (open  "manual_group_mng.dat" vb_fp "a")
 (run)
 (close vb_fp)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/alignment/get_dbase_mng.clp"))
 (load ?*path*)
 (load-facts "revised_root.dat")
 (load-facts "original_word.dat") 
 (load-facts "cat_consistency_check.dat")
 (load-facts "shallow_parser_root.dat")
 (run)
 (save-facts "database_mng.dat" local id-org_wrd-root-dbase_name-mng) 
 (save-facts "word_alignment_possibilities.dat" local man_id-word-root-anu_ids)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/alignment/alignment.clp"))
 (load ?*path*)
 (load-facts "manual_group_mng.dat")
 (load-facts "anu_grp_mng.dat")
 (load-facts "wx_agrep_output.dat")
 (load-facts "hin_mng_without_@.dat")
 (load-facts "aper_op_without_@.dat")
 (load-facts "shallow_parser_root.dat")
 (load-facts "database_mng.dat")
 (open  "alignment_debug.dat" alig_fp "a")
 (run)
 (close alig_fp)
 (save-facts "anu_and_man_rt_mng.dat" local eng_root-anu_root-man_root eng_root-anu_mng-sep-man_mng)
 (save-facts "alignment.dat" local anu_id-a_grp_mng-sep-manual_id-m_grp_mng)
 (clear)
 ;--------------------------------------------------------------------------
 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/alignment/word_alignment.clp"))
 (load ?*path*)
 (load-facts "alignment.dat")
 (load-facts "anu_and_man_rt_mng.dat")
 (load-facts "manual_group_mng.dat")
 (load-facts "aper_op_without_@.dat")
 (load-facts "hin_mng_without_@.dat")
 (load-facts "wx_agrep_output.dat")
 (load-facts "GNP_agmt_info.dat")
 (load-facts "shallow_parser_root.dat")
 (load-facts "database_mng.dat")
 (load-facts "manual_hindi_sen.dat")
 (load-facts "hindi_id_order.dat")
 (run)
 (save-facts "word_alignment.dat" local anu_id-anu_mng-sep-man_id-man_mng)
 (clear)
 (exit)
