 (load "global_path.clp")
 (bind ?*path* (str-cat ?*path* "/miscellaneous/SMT/phrasal_alignment/align_debug/parserid_wordid_mapping.clp"))
 (load ?*path*)
 (load-facts "sd_numeric_word.dat")
 (load-facts "original_word.dat")
 (load-facts "punctuation_info.dat")
 (open "parserid_wordid_mapping_with_punct.dat" link_word_fp "w")
; (watch rules)
; (watch facts)
 (run)
 (exit)
